### ISSUE TITLE
[Feature] Display Capital Gains/Loss

### ISSUE THREAD

**Issue by seniorm0ment** [cake-tech/cake_wallet#1148]
Would be really nice to see capital gains/losses to compare against how much you vested. Good to see if you have lost or gained money.

**Comment by tuxpizza** [comment]
Thanks for the suggestion, but this is quite out of scope for this project, especially since Cake Wallet isn't designed for investing but primarily for actual crypto day to day usage, we don't know everytime when the user actually paid for the crypto in FIAT, vs  when they simply deposited into their wallet.
