### ISSUE TITLE
Cake wallet iOS 

### ISSUE THREAD

**Issue by Tomvtec** [cake-tech/cake_wallet#1446]
Tried to open my cake wallet on iPhone but it’s just a blank screen I just deposited into ten minutes beforehand and it was fine now it’s not working

**Comment by sarahdiskin** [comment]
i'm having the same problem. have you found a fix yet?

**Comment by crispE45** [comment]
same thing has happened to me, can’t find a fix

**Comment by Tomvtec** [comment]
The only way it worked for me is to delete the app and reinstall and restore your wallet from your private seed

**Comment by Tomvtec** [comment]
> same thing has happened to me, can’t find a fix

Delete app and reinstall restore wallet from your private seed

**Comment by NChampion** [comment]
Be forewarned: the issue may come back.  It did for me.

Yesterday I exchanged BTC > LTC and when I came back Cake wouldn't open.  I tried restoring the backups I have one my phone but those gave me a checksum error.  Eventually I restored them via the seed words.  It displayed my balance as $0 for hours with the status "synchronized" which was concerning.  Restoring a wallet with its seed doesn't restore the exchange history.  Eventually it did update and everything seemed to be working again.  Last night I went and exchanged more BTC for LTC and when I came back it's having the exact same problem.

**Comment by Tomvtec** [comment]
> Be forewarned: the issue may come back. It did for me on Android at least.
> 
> Yesterday I exchanged BTC > LTC and when I came back Cake wouldn't open. I tried restoring the backups I have one my phone but those gave me a checksum error. Eventually I restored them via the seed words. It displayed my balance as $0 for hours with the status "synchronized" which was concerning. Restoring a wallet with its seed doesn't restore the exchange history. Eventually it did update to reflect the correct balance and everything seemed to be working again. Last night I went and exchanged more BTC for LTC and when I came back it's having the exact same problem.

I’m using iPhone and cake is still working for me at the moment

**Comment by evan-annix** [comment]
Same issue here, when opening Cake Wallet on iOS the entire screen is now just white, no GUI appears whatsoever. This issue occurred for me when I enabled the Camera permission for Cake Wallet in the iOS Privacy menu.

**Comment by sarahdiskin** [comment]
i ended up being able to fix it! had to delete the app and restore my wallets with the seed and date created. hope this works for you too!

**Comment by sarahdiskin** [comment]
> Be forewarned: the issue may come back. It did for me on Android at least.
> 
> Yesterday I exchanged BTC > LTC and when I came back Cake wouldn't open. I tried restoring the backups I have one my phone but those gave me a checksum error. Eventually I restored them via the seed words. It displayed my balance as $0 for hours with the status "synchronized" which was concerning. Restoring a wallet with its seed doesn't restore the exchange history. Eventually it did update to reflect the correct balance and everything seemed to be working again. Last night I went and exchanged more BTC for LTC and when I came back it's having the exact same problem.

my history showed up once my wallet finished syncing!

**Comment by NChampion** [comment]
> > Be forewarned: the issue may come back. It did for me on Android at least.
> > Yesterday I exchanged BTC > LTC and when I came back Cake wouldn't open. I tried restoring the backups I have one my phone but those gave me a checksum error. Eventually I restored them via the seed words. It displayed my balance as $0 for hours with the status "synchronized" which was concerning. Restoring a wallet with its seed doesn't restore the exchange history. Eventually it did update to reflect the correct balance and everything seemed to be working again. Last night I went and exchanged more BTC for LTC and when I came back it's having the exact same problem.
> 
> my history showed up once my wallet finished syncing!

My sent/received history showed up, which makes sense as that's stored on the chain.  You can look that up on multiple sites via your public address.  But you had exchange history populate from when you converted one currency to another and it brought back the transaction details?

My concern was that I was in the process of converting BTC to LTC and when I came back to check on the status of that conversion I couldn't open Cake wallet.  When I restored my wallets with their seeds I saw my BTC wallet sent the bitcoin to the exchange.  My LTC wallet showed that it was "synchronized" with a $0 balance and hadn't received anything.  I would normally check my BTC wallet, look at the transaction and check the status of the exchange but all of my exchange history was gone.  I'm pretty sure that's stored locally on the phone.  I had the transaction id copied to my phone's clipboard but I updated my phone's OS in-between initiating the exchange and going back to check the status and the clipboard was cleared during the update.  That was a dumb decision on my part considering the problems I've had with Cake recently but the exchange went through fine and my LTC balance updated eventually.  

I'm just a little upset that my LTC wallet's status was "synchronized" and showed no indication that it was still catching up the transactions.  Also the fact that I have to restore my wallets from their seeds _again_ today.  Again, my LTC wallet says "synchronized" but it only has transactions through the middle of last month.  Unfortunately I figured it was a fluke so I didn't get around to taking a backup last night but I will do that immediately after it's caught up because history suggests as soon as I exchange any crypto it'll crash until I restore it all over again.  Although, I'm not confident that a backup will restore properly anyway.

**Comment by sebandrei** [comment]
Also getting blank white screen after using exchange feature. Never had issues with cake before using this feature.

**Comment by tuxpizza** [comment]
Hey guys! Please update to the version 4.16.1 that just came out today to see if that fixes blank screen issues!

**Comment by sebandrei** [comment]
> Hey guys! Please update to the version 4.16.1 that just came out today to see if that fixes blank screen issues!
> 
> Let me know if you still run into blank screens after that update

I downloaded the latest version and was able to open the wallet again!
