### ISSUE TITLE
Why is Haven being removed?

### ISSUE THREAD

**Issue by mcneb10** [cake-tech/cake_wallet#1523]
I have recently noticed some PRs to disable and remove Haven. However, I haven't seen any announcement as to why.

**Comment by tuxpizza** [comment]
Haven has been broken for a while, due to recent hardforks, and with the amount of Haven users we estimated to have with the amount of work required to fix it (we are a small team), we will probably drop it from the wallet (We have already disabled wallet creation), but will be doing it in a way that preserves the user's seeds so they can back them up incase they didn't already did.

**Comment by tuxpizza** [comment]
Closing this for now, if keeping haveno is wanted, feel free to add a feature request in our new Discussions category (which other people can upvote so we can see interest) https://github.com/cake-tech/cake_wallet/discussions/categories/feature-requests
