### ISSUE TITLE
Implementing BIP-47

### ISSUE THREAD

**Issue by retrnull** [cake-tech/cake_wallet#1740]
I would like to work on implementing send and receive support for BIP-47 payment codes. However, before I start the work, I have a few questions:

- Would such a feature be accepted into the codebase?
- I expect to take about a month to implement it. Approximately when would a release including the functionality be made available for download?

Thanks in advance. Please let me know of any concerns about BIP-47 and this particular endeavor. I'll start working on the implementation once I get answers.

**Comment by sethforprivacy** [comment]
Hey @retrnull, thank you for opening up this issue!

Obviously our focus for reusable payment codes is Silent Payments at the moment due to their many advantages over BIP 47, though we are still considering _at least_ implementing sending to BIP 47 payment codes in-house in the future. As a result I don't think we need an outside contributor to jump in at this stage for BIP 47, but we will keep this in mind if we decide to implement and need more resources on it.
