### ISSUE TITLE
[Feature] Implement background wallet sync via view keys in Cake Wallet for Android

### ISSUE THREAD

**Issue by sethforprivacy** [cake-tech/cake_wallet#192]
A bounty has been opened for this feature request, with funding being provided via donations by the Monero community:

https://bounties.monero.social/posts/9/implement-background-wallet-sync-via-view-keys-in-cake-wallet-for-android

Copying description here from that bounty:

> The current user experience on mobile wallets without light-wallet servers is very poor unless a user regularly opens his wallet to allow it to sync.
> 
> A strong solution for this would be to allow mobile wallets to perform background syncs (especially when on wifi/plugged in, like at night) using only view keys, so no spend keys are kept "hot" without the user's active consent/auth.
> 
> Once this is implemented, the user can expect to at most have to sync <1d of blocks before spending.
> 
> Payout criteria:
> 
> -     Wallet is able to sync up in the background, without the wallet open
> -     User can specify to only sync on wifi and/or when plugged in
> -     Code is open-sourced

**Comment by SamsungGalaxyPlayer** [comment]
We will consider this for android, but it really won't work smoothly for iOS. It's on our to-do.

**Comment by SamsungGalaxyPlayer** [comment]
Related to:

https://github.com/monero-project/monero/issues/8082
https://github.com/monero-project/monero/pull/8617
https://github.com/monero-project/monero/pull/8619

I'm going to close this issue, since it's being addressed on the Monero wallet side. We have a remaining open issue on background syncing generally, which can use this improved approach.
