### ISSUE TITLE
[Question] Are wallet seeds stored encrypted?

### ISSUE THREAD

**Issue by VampireSilence** [cake-tech/cake_wallet#331]
Just a quick question, i guess the subject says it all. The question came up because of a virus on my phone.

**Comment by juanpc2018** [comment]
hackers use different method of stealing seeds / private keys.

for example:
Monerujo XMR wallet,
it has the most strong encryption method,
keys are combined with hardware id when stored.
even if hackers steal the keys file, cannot decode, because dont have hardware id keys...

BUT....
that makes hackers more aggressive,
for example:
they hacked all github servers last year, and replaced the .apk of monerujo 
with a malicious code that decrypts the keys inside each phone as txt,
but only does after a few months later, so the attack goes under the radar.,
phone sends the private keys as login and password to the servers,
hackers had servers listening the passwords...

conclusion:
#1. if you connect to unknown servers you increase your risk. "hackers can know how much you have, etc..."
you are easy to phish.
#2. phone wallets are just that, 
wallets,
Not bank vault safe deposit boxes.

you don´t put all your money in a mobile wallet.
also dont put all your money in a online centralized virtual vault that can be hacked,
because they know where it is.... see bitfinex hack.

private keys, can be secured off-line, 
there are many different methods... analog & digital.
No matter how good the hacker is, cannot have access.
unless you get drunk in a party and scream how much coins you have and where.

**Comment by SamsungGalaxyPlayer** [comment]
Thank you for your question. Yes.

**Comment by VampireSilence** [comment]
Thats interesting stuff and important to know for everyone for sure, but it doesn't answer my question with a yes nor a no.
