### ISSUE TITLE
[$150 Bounty] Add Tagalog (tl/tgl)

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [cake-tech/cake_wallet#704]
Please see the steps here on how to add the language:

https://github.com/cake-tech/cake_wallet#add-a-new-language

The following conditions apply:

* You may start with a machine translation, but you must review the changes and make modifications where necessary. Some strings require knowledge of context in the wallet.
* Bounties are paid in XMR.
* You must sign a consulting agreement with Cake and provide your name if you complete more than 1 translation. Email justin@cakewallet.com for this.
* Reference this issue in your pull request.
* You must reply to this issue indicating that you will work on it. This will reserve the bounty for 1 week. After 1 week, another person may reserve this bounty.
* You will submit a pull request of your own work and sign any/all copyrights over to Cake Labs LLC with no restrictions.
* You must not be an existing or past Cake employee (without prior approval).
* The bounty will only be paid after the pull request is merged. Cake reserves the right to close pull requests and to not pay a bounty for any reason.
* This is separate from [Monero Bounties](https://bounties.monero.social/) and any other similar program. If another program covers this same work, you'll need to work with the other system administrators for their own programs. If anyone wishes to further incentivize this work, we recommend they use a system like [Monero Bounties](https://bounties.monero.social/) and comment the relevant bounty link below.
* If you have questions about this bounty (eg: scope of work), please comment below.

If you wish to reserve this bounty, please reply with:

> I reserve this bounty for 1 week and agree to these terms and conditions.

**Comment by nahuhh** [comment]
I reserve this bounty for 1 week and agree to these terms and conditions.

**Comment by Meliza2022** [comment]
I reserve this bounty for 1 week and agree to these terms and conditions.

**Comment by rbrunner7** [comment]
Maybe I am not supposed to dump this here, but maybe it's useful for the person who ends up making this translation, so there: (It's not about any bounty for me, but just an attempt to contribute something)

I googled for "role models", for places where we can see whether there is already some pre-established cryptocurrency wallet terminology for Tagalog. If yes, no need to re-invent the wheel or deviate from something where maybe we should follow / copy regarding key terms.

I wasn't very successful. I could not find any wallet app that is already localized.

This may be interesting, but needs an account to look at the actual strings, and I did not go that far: https://crowdin.com/project/breadwallet/tl

You can switch the Coins.ph website to Tagalog, but that was quite a disappointment. One of the premier Philippine crypto websites, and such a bad localization ...

This website localization looks a bit better: https://paxful.com/tl

I stumbled over this video: https://www.youtube.com/watch?v=Fl38LdNl09g and it was more or less as I expected: About half of the words are Tagalog, and the other half English, probably because for many things crypto there are no good established Tagalog terms, so people use the English terms quite naturally.

So maybe just a little hint for the Cake Wallet Team: If the "Tagalog" localization you receive has what looks like a very high amount of words in it that are still in English that may still be appropriate, not just a work done lazily or a work not completed. 

Please also take into account that most people in the Philippines have English as second language anyway.

**Comment by WaffleManEaters** [comment]
I reserve this bounty for 1 week and agree to these terms and conditions.

**Comment by rbrunner7** [comment]
@SamsungGalaxyPlayer or whoever watches this: I reviewed the PR #748 and left 79 comments so far, but now it seems nobody else except me is able to see my review comments. Can somebody confirm, and if there really is a problem, can something be done to make the comments visible? I diligently and seriously worked for several hours on that review, and it would be a pitty if that was all for naught ...

**Comment by rbrunner7** [comment]
You can probably forget my comment from half an hour ago, my review is visible now after I told GitHub it's "finished".

**Comment by SamsungGalaxyPlayer** [comment]
Yes you submitted a review

**Comment by nahuhh** [comment]
@SamsungGalaxyPlayer 
Almost finished with review comments.
Will submit updated commits later today

https://github.com/nahuhh/cake_wallet/commit/2fcffec598e6391a66da3bc786b50486c2ca473a

Current status ^

**Comment by rbrunner7** [comment]
I just saw that the Hausa localization ran into a technical problem of Hausa not being a supported locale by Flutter by default. See [this comment](https://github.com/cake-tech/cake_wallet/pull/740#issuecomment-1403783559) over at the Hausa PR.

I checked [this documentation](https://api.flutter.dev/flutter/flutter_localizations/GlobalCupertinoLocalizations-class.html) linked there and saw that Tagalog seems to be supported, but under the name of the "official" language, i.e. *Pilipino*, with a language code of *fil* (which looks a bit strange, as there is only 1 additional code there with 3 instead of 2 letters ...)

@SamsungGalaxyPlayer , what do you think: Does this mean anything for this Tagalog localization and the people working on it now, or is this out of scope, and your devs will care about it?

**Comment by nahuhh** [comment]
> I checked [this documentation](https://api.flutter.dev/flutter/flutter_localizations/GlobalCupertinoLocalizations-class.html) linked there and saw that Tagalog seems to be supported, but under the name of the "official" language, i.e. *Pilipino*, with a language code of *fil*

It appears Tagalog is also listed on that page as `tl - Tagalog`

**Comment by rbrunner7** [comment]
> It appears Tagalog is also listed on that page as `tl - Tagalog`

Right, completely overlooked, my bad, so probably no problem at all.
